### ISSUE TITLE
print object in console

### ISSUE THREAD

**Issue by VictorAmelin** [vvorld/getid-ios-sdk#1]
try to type po (and variable)

virtual filesystem overlay file '/Users/mikhail/Library/Developer/Xcode/DerivedData/GetID-SDK-cchayjietrubkpaayguzfzftyfyx/Build/Intermediates.noindex/GetID-SDK.build/Release-iphonesimulator/GetID.build/all-product-headers.yaml' not found

**Comment by wacumov** [comment]
Hi @VictorAmelin. We'll try to fix it in the next release. 

For now, please use the following workaround:
Press `⌘N`, select "Cocoa Touch Class", pick Objective-C language, name the class "Empty", let it be a subclass of NSObject. Then confirm when Xcode asks about the Bridging Header. That's all.

**Comment by Kiriakovd88** [comment]
The issue was fixed in newer versions.
